---
ID: "0b2d66a6-bc4a-4c80-95c1-6a4a2f5eb4a4"
Parent: "18e8f49e-3ce9-4a94-b2e7-2f3a7c3e2d6d"
Template: "18e8f49e-3ce9-4a94-b2e7-2f3a7c3e2d6d"
Path: "/sitecore/templates/Project/click-click-launch/Edit Mode Rendering Exclusions/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260905T000000Z